# Generated by Django 4.1.4 on 2022-12-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('s_n', models.CharField(max_length=10)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
